title: Homescreens
description: >
    Browse the best homescreens posted on /wg/ here. Currently listing 92 beautiful homescreens, with more to come.
baseurl: ""

# Build settings
exclude: ["README.md", "old-site", "portfolio.sublime-project", "portfolio.sublime-workspace"]
permalink: pretty
gems:
  - jekyll-sitemap
